import Link from "next/link";
import SiteFrame from "@/components/SiteFrame";

export const metadata = { title: "About Dholera Estates | Residential Plot Guidance", description: "Learn how Dholera Estates supports buyers with project information, plot selection, documentation guidance and site visits near Dholera SIR." };
const services = [["Research","We study the project location, available plot options and the wider Dholera development context."],["Understand","We explain indicative pricing, plot sizes, location details and documents in clear language."],["Visit","Our team coordinates guided site visits so buyers can assess the location on the ground."],["Support","We remain available through enquiry, selection and independent document verification."]];

export default function AboutUsPage(){return <SiteFrame><main className="about-page">
  <section className="about-banner" style={{backgroundImage:"url('/images/14.jpg')"}}><div className="about-banner-overlay"/><div className="shell about-banner-content"><span className="eyebrow light-text">Get to know us</span><h1>About Dholera Estates</h1><p>Helping buyers explore residential plot opportunities with clarity, local context and guided support.</p><div className="breadcrumbs"><Link href="/">Home</Link><span>/</span><b>About Us</b></div></div></section>
  <section className="section about-story"><div className="shell about-story-grid"><div className="about-story-image" style={{backgroundImage:"url('/images/13.jpg')"}} role="img" aria-label="Dholera residential plotted development"><div className="about-year"><strong>2024</strong><span>Established</span></div></div><div className="about-story-copy"><span className="eyebrow">Our company</span><h2>Building Trust, One Conversation at a Time</h2><p>Dholera Estates was established in 2024 to help buyers explore residential land opportunities connected to the wider Dholera development region.</p><p>We focus on clear project information, suitable plot selection, site-visit coordination and guidance on the documents buyers should independently verify before making a decision.</p><div className="about-values"><div><b>Clear</b><span>Project information</span></div><div><b>Guided</b><span>Site visits</span></div><div><b>Buyer-first</b><span>Support</span></div></div></div></div></section>
  <section className="section about-purpose"><div className="about-purpose-glow"/><div className="shell about-purpose-grid"><div><span className="eyebrow light-text">What we do</span><h2>Our Objective</h2><p>To make residential plot discovery easier to understand by connecting buyers with current project details, on-ground guidance and a due-diligence-first approach.</p></div><div className="about-solution"><span>Our approach</span><h3>A Clear Path From Enquiry to Site Visit</h3><ul><li>Residential plot options</li><li>Location and availability guidance</li><li>Plot-size and price information</li><li>Document-review checklist</li><li>Guided site-visit coordination</li><li>Continued buyer assistance</li></ul></div></div></section>
  <section className="section about-process"><div className="shell"><div className="about-process-head"><div><span className="eyebrow">How we help</span><h2>A Simple, Buyer-Friendly Process</h2></div><p>Each step is designed to give you better context before you make a property decision.</p></div><div className="about-process-grid">{services.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="about-final-cta"><div className="shell"><div><span className="eyebrow light-text">Ready to explore?</span><h2>Plan Your Dholera Site Visit</h2><p>Speak with our team about current plot availability, pricing and location details.</p></div><Link href="/contact-us" className="btn">Talk to Our Team</Link></div></section>
</main></SiteFrame>}
