import Link from "next/link";
import SiteFrame from "@/components/SiteFrame";
import PropertyPageMotion from "@/components/PropertyPageMotion";

export const metadata = { title: "Residential Plots Near Dholera SIR, Gujarat", description: "Explore Dholera Estates residential plots in Akru village near Dholera SIR." };
const facts = [["Location","Akru village, near Dholera SIR, Gujarat"],["Land type","NA-converted residential plots*"],["Plot sizes","Approximately 170–235 sq. yd."],["Indicative price","Approximately ₹13–17 lakh onwards*"],["Township area","Approximately 16 acres*"],["Project","Dholera Estate Residential Plots"]];
const buyers = ["First-time land buyers seeking an accessible entry into the Dholera region","NRIs who want to research the location and documentation before purchasing remotely","Families considering long-term residential land in a planned township setting"];
const infrastructure = ["Ahmedabad–Dholera Expressway corridor","Developing Dholera International Airport","DSIRDA-led infrastructure within the notified SIR","Industrial investment in the wider Dholera region","Delhi–Mumbai Industrial Corridor connectivity"];
const faqs = [["What is Dholera Estates?","Dholera Estates is a residential plotted-development project promoted in Akru village, near the Dholera Special Investment Region in Gujarat."],["Is Dholera Estates inside Dholera SIR?","No. The project is described as being near the Dholera SIR boundary, not inside the separately notified SIR planning zone."],["What is the indicative starting price?","Current project information indicates approximately ₹13–17 lakh onwards, depending on plot size and availability. Obtain a written price sheet before deciding."],["Does buying a plot guarantee returns?","No. No land purchase guarantees appreciation or returns. Outcomes depend on infrastructure execution, market conditions and the specific location."],["Who may find the project suitable?","It may suit first-time land buyers, NRIs researching the Dholera region and families seeking a planned residential plot."]];

export default function PropertiesPage(){return <SiteFrame><PropertyPageMotion/><main className="property-page">
  <section className="property-banner" style={{backgroundImage:"url('/images/p1.jpg')"}}><div className="property-banner-shade"/><div className="shell property-banner-inner"><div className="breadcrumbs"><Link href="/">Home</Link><span>/</span><b>Properties</b></div><span className="eyebrow light-text">Dholera Estates</span><h1>Residential Plots Near Dholera SIR, Gujarat</h1><p>Explore NA-converted residential plot options promoted in Akru village, near the Dholera Special Investment Region.</p></div></section>
  <section className="section property-list-section"><div className="shell"><div className="property-list-heading"><div><span className="eyebrow">Featured property</span><h2>Dholera Estate Residential Plots</h2></div><p>A planned township with plot options suited to different residential and long-term requirements.</p></div><article className="listing-card"><div className="listing-image" style={{backgroundImage:"url('/images/p1.jpg')"}}><span className="listing-status">For Sale</span><div className="listing-price"><small>Starting near</small><strong>₹13 Lakh*</strong></div></div><div className="listing-body"><small>RESIDENTIAL PLOTTED DEVELOPMENT</small><h2>Dholera Estates Residential Plots</h2><p>Residential plots in a promoted 16-acre township near Dholera SIR, with a clubhouse and proposed temple included in the project information.</p><div className="listing-specs"><div><b>170–235</b><span>Sq. Yd.</span></div><div><b>Akru</b><span>Village</span></div><div><b>NA*</b><span>Land use</span></div></div><a href="#project-details" className="btn">View Project Details</a></div></article></div></section>
  <section id="project-details" className="section pale"><div className="shell content-layout"><article className="property-article"><span className="eyebrow">Project overview</span><h2>What Is Dholera Estates?</h2><p className="lead-copy">Dholera Estates is a residential land project located near—not inside—the Dholera SIR boundary. It promotes NA-converted residential plots of approximately 170 to 235 sq. yards within a planned township.</p><p>Buyers should confirm exact survey details, sanctioned layout, NA documentation, plot dimensions and position relative to the SIR boundary before purchasing.</p><div className="fact-table">{facts.map(([label,value])=><div key={label}><b>{label}</b><span>{value}</span></div>)}</div>
  <h2>Is Dholera Estates Inside Dholera SIR?</h2><p>No. The project is described as being near the Dholera SIR boundary. Dholera SIR is a separately notified industrial and planning zone with its own development framework under DSIRDA. Request exact map coordinates and written boundary clarification.</p>
  <h2>Why Do Buyers Consider Land Near the SIR?</h2><p>Some buyers consider land near the boundary because it can offer direct residential plot options without being part of the SIR’s internal planning timetable. That does not automatically make a plot easier, safer or more profitable: title, land use, access and layout approval still require independent verification.</p>
  <h2>Who Is It Best Suited For?</h2><ul className="content-checks">{buyers.map(x=><li key={x}>{x}</li>)}</ul>
  <h2>Regional Infrastructure Context</h2><p>Interest in the wider Dholera region is influenced by transport, industrial and planning initiatives. Dholera Estates is not presented as part of the SIR industrial core; proximity is the relevant consideration.</p><div className="infrastructure-grid">{infrastructure.map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div>
  <div className="returns-note"><h2>Does Buying Guarantee Returns?</h2><p><strong>No.</strong> No land purchase comes with guaranteed appreciation or a fixed return date. Market conditions, infrastructure timelines and the specific plot location all matter.</p></div>
  <h2>How Can I Verify a Plot?</h2><p>Request the latest layout plan, price sheet, plot coordinates and supporting documents. Have an independent property lawyer review the title chain and land-use paperwork rather than relying on a webpage or verbal promise alone.</p></article>
  <aside className="property-sidebar"><div className="sidebar-box"><span className="eyebrow">Project snapshot</span><h3>Get the latest details</h3><p>Request current availability, a layout plan and location guidance directly from the team.</p><Link href="/contact-us" className="btn">Enquire Now</Link><a href="tel:+919217104219" className="sidebar-call">Call +91 92171 04219</a></div><div className="sidebar-box light"><h3>Before You Buy</h3><ul><li>Verify title documents</li><li>Confirm NA conversion</li><li>Check exact boundaries</li><li>Review the sanctioned layout</li><li>Get pricing in writing</li></ul></div></aside></div></section>
  <section className="section faq-section"><div className="shell faq-layout"><div><span className="eyebrow">Common questions</span><h2>Frequently Asked Questions</h2><p>Clear answers to common questions about Dholera Estates.</p></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
  <section className="property-cta"><div className="shell"><div><span className="eyebrow light-text">Need exact information?</span><h2>Request the Plot Layout and Boundary Details</h2><p>We’ll walk you through the currently available documents and project information.</p></div><Link href="/contact-us" className="btn">Talk to Our Team</Link></div></section>
  </main></SiteFrame>}
